name: Linux

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install --yes cmake ninja-build g++ uuid-dev libavahi-client-dev

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DRDMNETBROKER_BUILD_TESTS=ON

      - name: Build
        run: cmake --build build --parallel 2

      - name: Test
        run: ctest --test-dir build --output-on-failure
